version: '3.9'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:5050'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  data:
