# Generated by Django 4.2.7 on 2023-12-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(upload_to='images/news'),
        ),
    ]
