# Generated by Django 4.2.4 on 2023-10-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('torque', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=10)),
                ('top_speed', models.CharField(max_length=10)),
                ('wet_weight', models.CharField(max_length=10)),
                ('fuel_capacity', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('quantity', models.IntegerField()),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.motorcycle')),
            ],
        ),
    ]
