# Generated by Django 4.2.4 on 2023-10-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
