# Generated by Django 4.2.4 on 2023-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_motorcycle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
