# Generated by Django 4.2.4 on 2023-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_motorcycle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='slug',
            field=models.SlugField(),
        ),
    ]
