# Generated by Django 4.2.4 on 2023-10-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_motorcycle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='capacity',
            field=models.IntegerField(max_length=4),
        ),
    ]
