# Generated by Django 4.2.4 on 2023-10-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_motorcycle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='fuel_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='top_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='torque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='wet_weight',
            field=models.IntegerField(),
        ),
    ]
