# Generated by Django 4.2.7 on 2023-11-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_motorcyclereservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(upload_to='images/rental'),
        ),
    ]
