# Generated by Django 4.2.7 on 2023-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_alter_motorcycle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
