# Generated by Django 4.2.7 on 2023-12-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_remove_motorcycle_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcyclereservation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
