# Generated by Django 4.2.7 on 2023-11-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_service_image_serviceimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='hour',
        ),
    ]
