# Generated by Django 4.2.7 on 2023-11-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_remove_servicereservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereservation',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
