# Generated by Django 4.2.7 on 2023-11-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_servicereservation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereservation',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
