# Generated by Django 4.2.7 on 2023-12-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_servicereservation_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereservation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
