from .account_detail.account_detail_view import UserAccountView
from .update_motorcycle_reservation.update_motorcycle_reservation import UpdateMotorcycleReservationView
from .update_service_reservation.update_service_reservation_view import UpdateServiceReservationView
from .delete_service_reservation.delete_service_reservation_view import DeleteServiceReservation
from .delete_motorcycle_reservation.delete_motorcycle_reservation_view import DeleteMotorcycleReservation


